backend:
  name: git-gateway
  branch: editor # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    label_singular: "Blog Post" # Used in the UI, ie: "New Blog Post"
    description: >
      This will add a new blog post to your blog, now go ahead and write something beautiful
    folder: "source/_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "DD/MM/YYYY hh:mma"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number", required: false}
